package shared.enums

//enum class PhasesEnum(val value: String) {
enum class PhasesEnum {
    PHASE_1_VICTORY_CHECK,
    PHASE_2_ADVANCE,
    PHASE_3_FLANK_ATTACKS,
    PHASE_4_PLAYER_ACTIONS,
    PHASE_4_DEFENDER_ACTIONS,
    PHASE_5_DRAW_CARDS,

//    PHASE_1_VICTORY_CHECK("PHASE_1_VICTORY_CHECK"),
//    PHASE_2_ADVANCE("PHASE_2_ADVANCE"),
//    PHASE_3_FLANK_ATTACKS("PHASE_3_FLANK_ATTACKS"),
//    PHASE_4_PLAYER_ACTIONS("PHASE_4_PLAYER_ACTIONS"),
//    PHASE_4_DEFENDER_ACTIONS("PHASE_4_DEFENDER_ACTIONS"),
//    PHASE_5_DRAW_CARDS("PHASE_5_DRAW_CARDS"),
}

